import React from "react";
import { ErrorBoundary } from "./ErrorBoundry";
import { render } from "@testing-library/react";

function ProblemChild() {
  throw new Error("Error thrown from problem child");
  return <div>Error</div>; // eslint-disable-line
}

describe("<ErrorBoundary> window", () => {
  it("displays error message on error generated by child", () => {
    const { getByText } = render(
      <ErrorBoundary>
        <ProblemChild />
      </ErrorBoundary>
    );

    expect(getByText("Something went wrong.")).toBeInTheDocument();
  });
});
